#!/bin/bash

test_logstash_is_running() {
  grep -q Debian /etc/issue && assert "service logstash status |grep -q 'running'"
  grep -q CentOS /etc/issue && assert "initctl status logstash |grep -q 'start/running'"
}

test_idempotence() {
  assert "sudo -u rpaulson ansible-playbook --verbose --diff -i 'localhost,' --connection=local /tmp/ansible/playbook.yml | grep -q 'changed=0.*failed=0'"
}

test_version_installed() {
  version_found=0
  [ -x /opt/logstash/bin/logstash ] && version_found=1 && assert_equals "$(/opt/logstash/bin/logstash --version)" "logstash 2.3.4"
  [ -x /usr/share/logstash/bin/logstash ] && version_found=1 && assert_equals "$(/usr/share/logstash/bin/logstash --version)" "logstash 5.6.0"
#  [ "$version_found" -eq 0 ] && fail "no version found"
}

run_ansible() {
  assert "sudo -u rpaulson ansible-playbook --verbose --diff -i 'localhost,' --connection=local /tmp/ansible/playbook.yml"
}

setup_suite() {

  mkdir /tmp/ansible/group_vars -p

  cat << EOF > /tmp/ansible/playbook.yml
- hosts: all
  pre_tasks:
    - name: Add backports
      apt_repository:
        repo: "deb http://ftp.debian.org/debian jessie-backports main"
      when: ansible_os_family == 'Debian'
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
    - name: Install jdk8 on Debian
      apt:
        name: "{{item}}"
        default_release: jessie-backports
      with_items:
        - ca-certificates-java
        - openjdk-8-jre
      when: ansible_os_family == 'Debian'
    - name: Install jdk8 on RedHat
      yum:
        name: java-1.8.0-openjdk-devel
      when: ansible_os_family == 'RedHat'
  roles:
    - role: ansible-role-logstash
EOF

[ "*el_2" == $(basename $0) ] && echo 2.X && cat << EOF >> /tmp/ansible/playbook.yml
      logstash_version: 2.3
EOF

  run_ansible

}


