---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: instance
    image: ami-000db10762d0c4c05
    instance_type: t2.large
    vpc_subnet_id: subnet-38a38302
    groups:
      - elasticsearch
provisioner:
  name: ansible
  connection_options:
    ansible_user: ec2-user
  playbooks:
    converge: converge.yml
    cleanup: cleanup.yml
  inventory:
    group_vars:
      elasticsearch:
        ca_crt: ../resources/ca/ca.crt
    host_vars:
      instance:
        server_crt: ../resources/instance/instance.crt
        server_key: ../resources/instance/instance.key
verifier:
  name: testinfra
  options:
    verbose: true
  directory: ../resources/tests/
